### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/choose#12]
@sdegutis, I can maintain this, although I may deprecate functionality I don't use to simplify the repo. I (and several others I know) use the CLI interface for quite a few tools like feeding in password selection from the www.passwordstore.org tool.

**Comment by sdegutis** [comment]
Ok @chipsenkbeil , just sent the transfer request.

**Comment by chipsenkbeil** [comment]
Mission accomplished. Thanks, @sdegutis.
