### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by rgomezcasas** [chipsenkbeil/choose#16]
Currently there is only [one release](https://github.com/chipsenkbeil/choose/releases/tag/1.0) which is also used from [brew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/choose-gui.rb). With that version, features like the changing the background color are inexistent.

Could you do a new release with the actual state of the code?

Thanks! 😊

**Comment by chipsenkbeil** [comment]
I don't own the formula mentioned, but I can at least add a new tag that someone else can use to update the formula.

https://github.com/chipsenkbeil/choose/releases/tag/1.1

**Comment by chipsenkbeil** [comment]
@focusaurus made a pull request to update the homebrew formula for the new tag: https://github.com/Homebrew/homebrew-core/pull/55845
