### ISSUE TITLE
choose-gui 1.3.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [chipsenkbeil/choose#37]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a

```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4664963366/jobs/8257857387
relates to Homebrew/homebrew-core#128042

**Comment by chipsenkbeil** [comment]
Hm, that's odd. You can see that it builds just fine and runs with this job: https://github.com/chipsenkbeil/choose/actions/runs/4663328797/jobs/8254554604. I just ran this job with the latest release yesterday and the binary works.

Maybe this is similar to https://github.com/flutter/flutter/issues/124474? What version of Xcode does the homebrew actions use? There's mention that Xcode 14.3 requires `MACOSX_DEPLOYMENT_TARGET = 10.13`, whereas this project currently has it set to `10.10`.

**Comment by chenrui333** [comment]
1.3.1 release build works well, thanks @chipsenkbeil!
