### ISSUE TITLE
Find/Execute apps as a default option or as an example in the readme

### ISSUE THREAD

**Issue by vlermandac** [chipsenkbeil/choose#39]
Hi, thank you for creating choose! I've been enjoying it a lot and is the best minimal selection tool that is native for macos. The main usage I give it is to open apps and run scripts. I couldn't believe that others apps charge for that second feature.

In that regard, there are 3 different directories where the apps are. The 'Application' folder you see in finder is a lie, it doesn't have any symlinks but the files inside may have different paths.

May be beyond the scope of the project, but with just a one liner you can list apps from your system in choose without the '.app' extension, and run them with the macos 'open' command (it can also run scripts. I didn't notice time differences with running scripts the normal way). So I thought that having that option out-of-the-box might be useful for some people.

Again, I know that it might defeat the purpose of minimal stdin/stdout selection, but it would be great if you think is ok to at least add it to the examples section in the readme file. I'd happily make a PR for that :)

**Comment by chipsenkbeil** [comment]
Happy to add an example to the readme on how to do this. Feel free to send over a PR 😄

**Comment by chipsenkbeil** [comment]
Resolved by https://github.com/chipsenkbeil/choose/pull/40.

Thanks!
