### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by 750** [chipsenkbeil/choose#46]
@chipsenkbeil Hi!
I want to add some features to this tool as I'm planning to use it for my everyday tasks (basically as a snippet manager - surprisingly there not many options to do this if one's looking for something opensource and easy to configure)

I guess what I'm asking is whether you as a maintainer have time to discuss features and merge PRs. If the answer is no - totally understandable, I'll just fork this.

Thank you!

**Comment by chipsenkbeil** [comment]
It's maintained, but I do so in bursts. Presenting at neovimconf + real work has kept me busy - I'm currently across the world from my home - so I can't promise I'll get to something promptly.

Feel free to run by me what you want to do. I'm fairly open to co-sharing repositories as well.
