### ISSUE TITLE
QoL improvements

### ISSUE THREAD

**Issue by 750** [chipsenkbeil/choose#47]
(this is a plan following https://github.com/chipsenkbeil/choose/issues/46)

Here's bunch of things I want to do:
1. (done) Allow customizing input separator - currently `\n`. This will allow for pasting multiline items. `\n` remains the default option
2. (done) We will now need to show whitespace characters as something other than whitespace characters. I'm thinking `\n -> ⏎, \t -> ⇥`, a la https://github.com/p0deje/Maccy. Disabled by default.
3. (done) Allow empty input (request number 1 here https://github.com/chipsenkbeil/choose/issues/27). Disallowed by default.
4. (won't be done in this issue) Show number of matches like `4/15`. This will require more than 2 lines of code, I have no experience with MacOS UI dev
5. (done) Make query field copypastable (https://github.com/chipsenkbeil/choose/issues/10) .

I intend to do 1 2 3 5, then maybe 4

**Comment by chipsenkbeil** [comment]
All seem reasonable to me 😄

**Comment by 750** [comment]
6. Support some basic regexps like ^ (actually I only need ^ to preselect items based on their first characters)

**Comment by 750** [comment]
Ok so I implemented 1235 - that's enough to make choose significantly better for me. I see 4 and 6 as nice-to-haves - so I won't be doing them now (maybe some other time)

Closing this - choose should probably get a new release now
