### ISSUE TITLE
Incorrect binary for release 1.4.0

### ISSUE THREAD

**Issue by sammmsational** [chipsenkbeil/choose#51]
When I download the binary directly from the 1.4.0 release, run `$ chmod +x ./choose` and then `$ ./choose -v` it still returns `./choose 1.3.1`. The same goes for the homebrew version.
This also means that the new features like running `$ choose -m` to just grab user input do not work for this version.

![image](https://github.com/user-attachments/assets/709ab001-89e9-43e2-9c27-08077e6d3eca)
_I renamed it `abc` to not conflict with the homebrew version_

**Comment by chipsenkbeil** [comment]
I forgot to update the binary version in Info.plist. The features should be there.

**Comment by sammmsational** [comment]
Running `$ choose -m` doesn't open anything for me. Am I using it incorrectly if I just want to grab user input?
