### ISSUE TITLE
Feature idea: remember (or set) position

### ISSUE THREAD

**Issue by chdiza** [chipsenkbeil/choose#8]
I'm playing around with `choose`.  It's pretty cool, but what would increase coolness by 1000% is if one could control the position of the choose box on the screen.  E.g., I'd want it in the upper left corner of the screen.

Currently, it can be dragged anywhere, but the position is not remembered between launches.

Perhaps a cmdline flag to set the screen coordinates of the box's northwest corner.  E.g., `ls | choose --location=0x22`.  At least this way, one won't have to mess with storing the position in a preference plist.

**Comment by sdegutis** [comment]
Great idea!
